### ISSUE TITLE
Bug with Taginput allowing duplicates

### ISSUE THREAD

**Issue by williamabbott** [buefy/buefy#1035]
Based on the linked pen from the docs (shortened sample data for clarity)

I pre-loaded an object in created() into the taginput model `tags`. Now try and add 'John' again. It creates a duplicate in `data.tags`

https://codepen.io/will-abbott/pen/aRqYJV

Not sure if I am missing something simple..

**Comment by jtommy** [comment]
@williamabbott The component compare the object and they are two different istance, for example try to add this line in `created` hook, `this.tags = [data[1]]`.
Anyway I advise to use `beforeAdding` prop so you can check the new tag and return true or false if new tag is ok or not.

**Comment by Sogl** [comment]
@jtommy I have the same problem.

When I use taginput component and load tags from my backend model to it (I use `mounted()` for it: `this.tags = this.post.tags;`) I can add the same tags again with `allow-new`... How to get rid of it? In create mode all works fine.

Some explanations:
1. `this.post.tags` (Array of Objects) — tags already added to post (I use `post` prop).
![image](https://user-images.githubusercontent.com/7556290/77708340-d9727f00-6fd8-11ea-975f-771e707b68ed.png)
2. `tag` (Object) — tag to add.
![image](https://user-images.githubusercontent.com/7556290/77708388-ff981f00-6fd8-11ea-871f-02bf1ae3f3df.png)
3. Sometimes tags isn't type of Object but String (because we can add new tags manually). So we need to check added tag and every position in Array of existing tags.
3. Finally in `beforeAdding` I need to return true (no Object/String in Array of Objects/Strings) for adding new tag.


## After some time

I found a workaround for this situation:
```js
import isObject from 'lodash/isObject';
...
beforeAdding(tag) {
    let tagStr = '';

    if (isObject(tag)) {
        tagStr = tag.name.ru;
    } else tagStr = tag;

    let found = false;
    for (var i = 0; i < this.tags.length; i++) {
        if (isObject(this.tags[i])) {
            if (this.tags[i].name.ru == tagStr) {
                found = true;
                break;
            }
        } else {
            if (this.tags[i] == tagStr) {
                found = true;
                break;
            }
        }
    }

    return !found;
},
...
```

This code works as it should...  but maybe a better way of solving exists. I will be glad of any help.

P.S. In some sequence of adding and removing existing and new tags, the function `beforeAdding` stops working completely (no `console.log` at all) until you “break through” it with one tag from the finished list. I have not yet found how exactly this bug works.

**Comment by scriptburn** [comment]
having same issue

**Comment by nikhilkutinha** [comment]
If you're working with an array of objects / remote data you'll need to manually check if the tag to be added exists in the array you hooked up to v-model.  Here's a quick example.

```js
<b-taginput
    v-model="people"
    autocomplete
    field="name"
    @typing="getAsyncPeople"
    :data="filteredPeople"
    :before-adding="doesExist"
></b-taginput>

doesExist(tagToAdd) {
    const add = this.people.find(({ id }) => id === tagToAdd.id) ? false : true;
    return add;
}
```
