### ISSUE TITLE
Best method for modifying style in component using scoped?

### ISSUE THREAD

**Issue by cdrandin** [buefy/buefy#1197]
### Overview of the problem

**Buefy** version: 0.7.2
**Vuejs** version: 2.5.17
**OS/Browser**: macOS 10.14.2 / Chrome Version 71.0.3578.98

### Description

I am trying to change a selector that is being used in a component. I was wondering if there is a way to change it while still maintaining scoped. This doesn't seem to be a buefy problem, but I am unsure how to get round this.

### Example

I am using the Tab component and i want to adjust `b-tabs` child selector `tabs`. The following works fine without scoped.

```css
.b-tabs .tabs {
    margin-bottom: 0;
}

```

Class selector hierarchy of the component

b-tabs
       |___ tabs
       |___ tab-content

**Comment by jtommy** [comment]
You should add a custom class to `bTabs` but i don't think it'll work in scoped.
Anyway you'll be able to apply a style only for a single tabs, for example:
```
.b-tabs.custom-class .tabs {
    margin-bottom: 0;
}

<b-tabs class="custom-class">...</b-tabs>
```

**Comment by cdrandin** [comment]
Thanks that worked.

**Comment by szmarczak** [comment]
Shouldn't this be considered as a bug? The parent is scoped but the children are not.

> You should add a custom class to bTabs but i don't think it'll work in scoped.

I can confirm this approach works in scoped mode.

**Comment by kvanalls** [comment]
Old thread but adding what I think is a better solution for the benefit of other Googlers...

### Solution: Use deep selectors to scope child elements

@szmarczak I had the same impression but it appears that not scoping children by default is by design and can be changed by using deep selectors, which worked for me:
https://vue-loader.vuejs.org/guide/scoped-css.html#deep-selectors

@cdrandin and @jtommy This means that an alternative approach to the custom classes would be the following (you may need to use /deep/ or ::v-deep instead of >>> depending on your pre-processor; see the link above):
```
.b-tabs >>> .tabs {
    margin-bottom: 0;
}
```

#### Selectors can start with ::v-deep

Selectors can start with the deep combinator, at least in sass using ::v-deep. A version of the following works for me:
```
::v-deep .tabs {
    margin-bottom: 0;
}
```
