### ISSUE TITLE
cleave.js v-model is not working on vue 2.6.x 

### ISSUE THREAD

**Issue by emrahyumuk** [buefy/buefy#1246]
### Overview of the problem

**Buefy** version: [0.7.2]
**Vuejs** version: [2.6.7]
**OS/Browser**: Chrome 72.0.3626.109 (64-bit)

### Description
Custom mask and v-model directive are not working correctly on vue.js 2.6.x 
https://codepen.io/emrahyumuk/pen/XGJXbL

**Comment by jtommy** [comment]
Where is the issue?

**Comment by emrahyumuk** [comment]
Vue v2.5.22 cleave.js custom mask 
https://codepen.io/emrahyumuk/pen/droyGw
![image](https://user-images.githubusercontent.com/2338849/53473318-248b2d00-3a7b-11e9-8f80-76210ef8ccd2.png)

Vue v2.6.7 cleave.js custom mask
https://codepen.io/emrahyumuk/pen/XGJXbL
![image](https://user-images.githubusercontent.com/2338849/53473416-60be8d80-3a7b-11e9-841a-41702d54d6ee.png)

Same codes but custom mask is not working on vue 2.6.x
It is working when I am removing v-model but mask is triggered after I type all of input text "12312123123"  
There is a problem with v-model and mask trigger time. But i don't know what the problem is.

**Comment by yxngl** [comment]
Might be related to $nextClick changes in Vue 2.6
https://github.com/buefy/buefy/blob/50df8ae8b4b140c86a84273107ce184b20de7628/src/components/input/Input.vue#L201-L211

**Comment by luisjoserivera** [comment]
Solution?

**Comment by jtommy** [comment]
I'll take a look as soon as possible

**Comment by luisjoserivera** [comment]
I've been trying to identify the cause.
I noticed that if you don't use v-model on the input the masking "works".
I say "works" because the input gets masked but if you check in the vue inspector, **newValue** property of the b-input component is not properly being updated when the masking occurs.
And if you are using a b-field wrapper around a masked b-input set as required, on blur the value of the input gets updated with whatever is in **newValue**.

**Comment by yxngl** [comment]
The CodePen example actually works on Firefox (Windows and Mac), but not other browsers.

**Comment by yxngl** [comment]
The solution I found without modifying the b-input is just not to use v-model...
https://codepen.io/yxngl/pen/MxrmxP

The reason behind the problem is v-model listens to Vue's input event and Cleave.js listens to native input event. B-input uses nextTick to update internal value and then emit input event. Vue 2.6 switch nextTick back to microtask, and now the order of native and Vue's input events are not consistent between browser engines. Depending on which input event fires earlier, the value v-model receives may not be formatted by Cleave.js.

The workaround I first came up is to add an event handler of the native input event (like showing raw value in the example) and updates the formatted value in data. Then v-model directive can just be replaced by v-bind as it is basically reimplemented.
