### ISSUE TITLE
Checkbox and Switch can't toggle with space key at Firefox on Linux and Windows

### ISSUE THREAD

**Issue by krororo** [buefy/buefy#1320]
### Overview of the problem

**Buefy** version: [0.7.4]
**Vuejs** version: [2.6.10]
**OS/Browser**: Linux and Windows / Firefox

### Description

Checkbox and Switch flashes when toggling with the space key.

Checkbox:
![checkbox](https://user-images.githubusercontent.com/3143443/55937146-36174580-5c73-11e9-9a8e-f4898581ba4c.gif)

Switch:
![switch](https://user-images.githubusercontent.com/3143443/55937149-38799f80-5c73-11e9-9be8-458bb302d83a.gif)

related PR: #1272 

### Steps to reproduce

1. Focus on Checkbox or Switch.
2. Press space key.

### Expected behavior

Checkbox and Switch can toggle with the space key.

### Actual behavior

Checkbox and Switch can't toggle with the space key.

**Comment by yxngl** [comment]
My bad. I reverted and didn't really fix the problem. I think the above PR should be reconsidered.

Now I also tend to prefer setting the input instead of the label to be the active element (which is actually selected), although it needs more work to refactor checkbox, radio and switch. Currently, even when the checkbox is first selected by keyboard, pressing enter/space will change the active element to the underlying input, so the glowing boarder effect disappears after interaction.

**Comment by yxngl** [comment]
My bad. I reverted and didn't really fix the problem. I think the above PR should be reconsidered.

Now I also tend to prefer setting the input instead of the label to be the active element (which is actually selected), although it needs more work to refactor checkbox, radio and switch. Currently, even when the checkbox is first selected by keyboard, pressing enter/space will change the active element to the underlying input, so the glowing boarder effect disappears after interaction.

**Comment by krororo** [comment]
What's wrong the above PR? As I only fixed checkbox?
