### ISSUE TITLE
Table pagination number has a weird dots and alignment has a bug

### ISSUE THREAD

**Issue by ethlyseria** [buefy/buefy#1388]
Good day,

I don't know why, but my table has a weird dot beside the pagination number of my table.

![paginationproblem](https://user-images.githubusercontent.com/42052787/57437113-b087b500-7273-11e9-85cb-5db176d286ae.JPG)

I'm using version `"buefy": "^0.7.1",`

**Comment by jtommy** [comment]
Is it inside a tab ?

**Comment by mujabdulh** [comment]
I think it's because container class, instead use another class, @ethlyseria  

In my case, here's div with container class
![pagination with  content](https://user-images.githubusercontent.com/47131024/58068895-82806a00-7bbd-11e9-865e-02a7d3dac200.PNG)

then, after remove container class
![pagination without  content](https://user-images.githubusercontent.com/47131024/58068900-8613f100-7bbd-11e9-9354-a4fdc362e052.PNG)

**Comment by jtommy** [comment]
https://github.com/jgthms/bulma/issues/1986
