### ISSUE TITLE
Taginput and cyrillic symbol "б"

### ISSUE THREAD

**Issue by ValeriyMaslenikov** [buefy/buefy#1485]
### Overview of the problem

**Buefy** version: 0.7.7
**Vuejs** version: 2.6.10
**OS/Browser**: Mac OS

### Description

In the Cyrillic keyboard layout (for example in the Russian language) to type letter `б` you should press the same button that types `,` in the Latin layout (keycode: 188). After pressing this button in the taginput component, I expect to see the typed letter in the default behavior (without overriding `confirmKeyCodes`) but actually got confirmed tag. 

In the Cyrillic layout, pressing Shift+6 causes typing a comma, but I would expect to see the confirmed tag. 

As a solution, we can handle the `keypress` event in combination with `keydown`. `keypress` event has information about char code, where `б` and `,` have different codes.  

### Steps to reproduce

1. Add simple component (without overriding `confirmKeyCodes`: 
```
<b-taginput
  v-model="tags"
  ellipsis
  icon="label"
  placeholder="Add a tag">
</b-taginput>
```
2. Type word which contains symbol "б", like "Абсолютно" and press enter.
3. This word should create only one tag, but got two:

![image](https://user-images.githubusercontent.com/5353364/59853948-9a910800-937a-11e9-8cfd-6cf0590a188f.png)

P.S. It's not duplication of #1148

**Comment by afwn90cj93201nixr2e1re** [comment]
Большинство компонентов написано фиг пойми как и не тестируются меинтейнером, при этом багфиксы без объяснений - не принимаются. Привыкай. 
https://github.com/buefy/buefy/blob/dev/src/components/taginput/Taginput.vue#L124
Свой массив передай.
И ниже тоже в separator, там где запятая, если нужно конечно.

**Comment by afwn90cj93201nixr2e1re** [comment]
![изображение](https://user-images.githubusercontent.com/9306996/59965236-52a9e680-951c-11e9-9428-4822c42b1c0b.png)
https://codepen.io/anon/pen/LKWKjw?&editable=true&editors=101

Сам коммит.
https://github.com/afwn90cj93201nixr2e1re/buefy/commit/a33d75197e82e15eaac0cc26519caa5308fd560a

**Comment by afwn90cj93201nixr2e1re** [comment]
@jtommy maybe you should merge it? I already tested.

**Comment by afwn90cj93201nixr2e1re** [comment]
@jtommy maybe you should merge it? I already tested.

**Comment by afwn90cj93201nixr2e1re** [comment]
@service-paradis create pr with this fixes, coz @jtommy take some drugs and started do some stupid things again, xD.

**Comment by service-paradis** [comment]
In fact, we would need to rewrite some component events that are using the deprecated [KeyCode](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode)

The problem with KeyboardEvent.key right now is to support IE11 (even Edge in fact) that uses an early version of the spec (for example, it uses "Esc" rather than "Escape"). Not a hard job, but would need to verify evry key used to be sure to support IE (by using `if (key === 'Escape' || key === 'Esc')` instread of `if (key === 'Escape')` for example.

There is also an open issue because it does not always work when combining keys (https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/742263/). I also got an issue when using comma. IE11 is returning me "Decimal" instead of "," since the decimal separator for french canadian is a comma.

So, the commit you made is probably a good start but wont work for any cases.

**Comment by afwn90cj93201nixr2e1re** [comment]
We can just create some array of keycodes and other stuff like that, and create some handler inside https://github.com/buefy/buefy/tree/dev/src/directives dir and that's all.
In this component we doesnt need in another separate key's, like esc and other stuff like that, esc gonna unfocus input with default beh.

**Comment by service-paradis** [comment]
@jtommy 
We should think about switching to [KeyboardEvent.key](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key) instead of the deprecated [keyCode](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode).

It would be a breaking change in some component where we can define key codes in prop (TagInput for example). So maybe we could label this issue as `breaking change`?

**Comment by jtommy** [comment]
Sure!

**Comment by afwn90cj93201nixr2e1re** [comment]
we should make more brekabke changes with fixes since 0.7.x in 0.9 release.

**Comment by sergpy** [comment]
maybe add a property to the component that blocks comma processing,
like as comma: bool 
seems it the simplest way

**Comment by service-paradis** [comment]
In the next breaking release, we will cange the way Buefy handles Key events. It will solve this problem without the need to add a new prop.
