### ISSUE TITLE
b-select not working as expected with v-model property in computed properties

### ISSUE THREAD

**Issue by FabioBaravalle** [buefy/buefy#1564]
### Overview of the problem

**Buefy**: 0.7.10
**Vuejs**: 2.5.22
**OS/Browser**: macOS Mojave, browsers: Safari/Chrome/Firefox

### Description

https://codesandbox.io/s/vue-template-yj8ug?from-embed

### Steps to reproduce

https://codesandbox.io/s/vue-template-yj8ug?from-embed

### Expected behavior

When I select a value inside the first b-select that is greater than the second one I'm expecting that the value inside the first b-select does not update since the condition is not satisfied.

### Actual behavior

The property is updated even if the condition is not satisfied and I'm not setting the property ending with _

**Comment by service-paradis** [comment]
The problem is not with Buefy but within your condition in this part of code:
```
set(selectedYearBefore) {
        if (this.selectedYearBefore < this.selectedYearAfter) {
          this.selectedYearBefore_ = selectedYearBefore;
        } else {
          console.log("Should set nothing");
        }
      }
```
In your condition, `this.selectedYearBefore` will contain the old value and not the currently selected one. If you have 2008 and 2010 as initial value. You change the first date to 2014, your condition will be:
```
if (this.selectedYearBefore < this.selectedYearAfter)
if (           2008         <          2010         )
```
You should use the received parameter `selectedYearBefore` instead in your condition:
```
if (selectedYearBefore < this.selectedYearAfter)
if (        2014       <          2010         )
```

**Comment by FabioBaravalle** [comment]
Thanks for pointed out the error, I made a copy paste on the sandbox without double check. 
But still not working even with this edit (that I made yesterday night but seems that codesandbox did not update to the latest version)

**Comment by yxngl** [comment]
The codesandbox does not seem to update for me. But with that update, it still won't work as you expect. You can change b-select to normal select and it is the same.

When you choose a value, first the value inside the select will update. Based on your condition, the `selectedYearBefore_` may not be updated as expected, but that will also not trigger the component update since the binding model is not changed (values unsynchronized). 

You could add `this.$forceUpdate()` after the logging statement. But usually it is recommended to redesign the logic.
