### ISSUE TITLE
please provide vee-validate 3.x example

### ISSUE THREAD

**Issue by neuronflow** [buefy/buefy#2045]
### Description

the vee-validate example uses the outdated 2.x package
https://github.com/buefy/buefy/blob/dev/docs/pages/extensions/veevalidate/VeeValidate.vue

### Why Buefy need this feature

buefy should use state of the art validation

**Comment by francoism90** [comment]
I really tried giving vee-validate another go, but the 3.x changes aren't that easy to implement anymore in my opinion. I'm using HTML5-validate types and a mixin as alternative.

**Comment by Maxiride** [comment]
> I really tried giving vee-validate another go, but the 3.x changes aren't that easy to implement anymore in my opinion. I'm using HTML5-validate types and a mixin as alternative.

For a brand new project built with Beufy would you recommend using vee validate 2.x or switching to a different validator?

**Comment by francoism90** [comment]
@Maxiride Just do whatever you like. :)

Vee-validate still works when looking at the documentation itself, other solutions are available as well. Displaying errors can be easy be shown by using `message`/`type` on _b-field_ or `dialog`, `notification`, etc. I don't like the path vee-validate has chosen, but that doesn't make it bad, it's just a personal preference how to validate stuff.

**Comment by Maxiride** [comment]
> I don't like the path vee-validate has chosen, but that doesn't make it bad, it's just a personal preference how to validate stuff.

@francoism90 
Since it is the first time I am in need of field validation and I am exploring the possibilities "unbiased" would you please explain why you dislike the path VeeValidate has chosen? I'd like to understand if some of your reasons might matter to me but I have yet to encounter them. I'd like to have all the cards laid out before commencing my project =)

---
Anyway for everyone else stumbling on this issue I've found the following in case it might be of any interest for others:

- VeeValidate team published 3.x [examples ](https://logaretm.github.io/vee-validate/guide/3rd-party-libraries.html#buefy)for popular UI frameworks including [Beufy](https://codesandbox.io/s/veevalidate-components-buefy-znj4u?fontsize=14)

- The sandbox link shows a "vanilla" VeeValidate 3.x implementation **and** a refactored method (see `Form.vue` and `RefactoredForm.vue`

- VeeValidate isn't [renderless ](https://logaretm.github.io/vee-validate/api/validation-provider.html#rendering) but it can be forced to be with the `slim` prop.

  - This option is needed to avoid [breaking ](https://github.com/logaretm/vee-validate/issues/2543) Beufy CSS, in particular I faced this need when using the `b-field grouped` template.

**Comment by service-paradis** [comment]
Yeah, it would be a good idea to reproduce their [example](https://logaretm.github.io/vee-validate/guide/3rd-party-libraries.html#buefy) in the Buefy documentation. VeeValidate links to doc and Github are also out of date.

**Comment by jtommy** [comment]
https://github.com/buefy/buefy/issues/1977#issuecomment-575716255
