### ISSUE TITLE
Allow lazy loading tabs

### ISSUE THREAD

**Issue by MartinTuroci** [buefy/buefy#2129]
### Description

It would be great to have a flag called "lazy" to lazy load tab items content (via dynamic components), so that as a user I would always see tab-item header, but the content would not load immediately after render.

### Why Buefy need this feature

It is a common case when you want to display large portions of data (e.g. in b-table), but when having a lot of tab-items, that are all loaded eagerly, your page performance is hurt. Using lazy loading, the data wouldn't be loaded immediately on page load, thus resulting in better performance and UX.

**Comment by jtommy** [comment]
@MartinTuroci did you try to set `destroyOnHide` prop to `true` on `b-tabs` ?

**Comment by miili** [comment]
@jtommy does this enable lazy loading? If so this would be awesome and should go into the documentation.

**Comment by jtommy** [comment]
It renders only the selected tab item

**Comment by MartinTuroci** [comment]
@jtommy `destroyOnHide` destroys whole `b-tab-item`. The desired functionality is so that I am able to see the header (which in case of destroyOnHide I don't) and after clicking on it, the body of the `b-tab-item` gets mounted.

**Comment by MartinTuroci** [comment]
@jtommy I have managed to create a workround via @change listener and keeping current activeTabIndex. Then in `b-tab-item` slot, I simply added `v-if` like this:
`<b-tab-item v-for="(item, index) in items">`
     `<template v-if="activeTabIndex === index">`

However, I still think it would be cleaner if there was a special `lazy-load` prop.

**Comment by jtommy** [comment]
@MartinTuroci `destroyOnHide` works in the same way but it'll load the first tab item

**Comment by MartinTuroci** [comment]
@jtommy you are correct. I must have made a mistake somewhere when I was checking. Sorry for wasting your time and thanks for help.

**Comment by Dunnymeister** [comment]
Destroy on hide isn't quite lazy loading. For example, destroyOnHide has the following behaviour:

1. Tab A is selected: the content in Tab A is loaded
2. Then Tab B is selected: the content in Tab A is destroyed and the content in Tab B is loaded
3. Then Tab A is re-selected: the content in Tab B is destroyed and the content in Tab A is loaded again

A lazy-load feature would mean that instead of the above, the following would happen:

1. Tab A is selected: the content in Tab A is loaded
2. Then Tab B is selected: the content in Tab A is left as-is and the content in Tab B is loaded
3. Then Tab A is re-selected: the content in Tab B is left as-is and there is no need to reload the content in Tab A because it was never destroyed

This would be a useful feature as API calls made by components in tabs would not make API calls when they are destroyed and re-created. Expensive API calls would be made once and the results would persist.

Is there a recommended way to achieve the lazyLoad behaviour?

**Comment by robingiraud** [comment]
Hello,
I'm having the same problem. destroyOnHide works fine, but as mentioned by @Dunnymeister, this is not quite lazy loading.
Is this feature scheduled for a future update ?  That would be fantastic!
@jtommy

**Comment by jtommy** [comment]
In my opinion is not important but any PRs are welcome

**Comment by eriksvedenlund** [comment]
I work around this by sending the tab index as a prop to my component in a tab. Then I use watch on the tab index prop, and call the API if tab index matches the tab of my component and it does not already have any data.
