### ISSUE TITLE
Navbar fixed top removes body class "has-navbar-fixed-top" when dismounting and doesn't re-apply it when mounting again

### ISSUE THREAD

**Issue by bartvanremortele** [buefy/buefy#2282]
### Overview of the problem

**Buefy** version: 0.8.12
**Vuejs** version: 2.6.11
**OS/Browser**:  macOS Catalina 10.15.3 (19D76)

### Description

Navbar with fixed-top removes body class "has-navbar-fixed-top" when routing and doesn't re-apply if a different Navbar gets mounted.

### Steps to reproduce
Add vue-router and two pages both with a fixed-top navbar. Switch between the two pages. and notice that the "has-navbar-fixed-top" class gets removed from the body and is not re-applied when the second navbar is mounted.

### Expected behavior
The body class "has-navbar-fixed-top" should stay or should get re-applied. 

### Actual behavior
The body class "has-navbar-fixed-top" gets removed.

**Comment by jtommy** [comment]
https://github.com/vuejs/vue-router/issues/1380

**Comment by bartvanremortele** [comment]
Thanks for the elaborate explanation. I still don't see how this is expected behaviour for the Navbar though. Why is the component watching `fixedTop`? I believe it's not the Navbar's responsibility to apply the body class.

**Comment by jtommy** [comment]
There is the same problem if I move the logic on beforeMount hook.
Without that attribute it calls beforeDestroy after beforeMount

**Comment by christianlevesque** [comment]
In case anyone else has this issue, I got around this by manually adding the `is-fixed-top` class to `<b-navbar>` and manually managing the `has-navbar-fixed-top` class on the document body. I created a component to contain my navbar implementation, which looks something like this:

```
<template>
  <b-navbar class="is-fixed-top">...</b-navbar>
</template>

<script>
export default {
  // ...
  destroyed() {
    document.body.classList.remove("has-navbar-fixed-top");
  },
  created() {
    document.body.classList.add("has-navbar-fixed-top");
  }
}
</script>
```

Is this the best possible solution? I don't know. YMMV. It works for me, so I can continue to use Buefy's navbar instead of creating a fully custom navbar with Bulma alone.
