### ISSUE TITLE
on-border/inside positioned labels do not shift when the corresponding b-field has position set to is-right

### ISSUE THREAD

**Issue by P3trur0** [buefy/buefy#2381]
### Overview of the problem

**Buefy** version: ^0.8.15
**Vuejs** version: ^2.6.11
**OS/Browser**: Ubuntu 18.04

### Description

When using `b-field` with `position` property set to `is-right` and `labelPosition` set either to `on-border` or `inside`, it seems that the label does not shift to right as the actual field component does.

Here you may see an example:

![image](https://user-images.githubusercontent.com/11474157/78582871-463a1480-7836-11ea-80c1-b1759b7bb928.png)

where the **Potenza massima** labels should be on the right.

### Steps to reproduce

1. Define a b-field
2. set labelPosition property to 'on-border' and position property to 'is-right'.

### Expected behavior

The label of the b-field should be aligned to right as the field itself does.

**Comment by bcourteaud** [comment]
### Overview of the problem
Buefy version: ^0.9.3
Vuejs version: ^2.6.11
OS/Browser: Windows 10



### Description
When using b-field with position property set to is-right and labelPosition set either to on-border or inside, it seems that the label does not shift to right as the actual field component does.

### Here you may see an example:

Hello, same problem since recent version :

![labelPosition](https://user-images.githubusercontent.com/6702796/92571411-63f72400-f283-11ea-994a-a632c3c37f6b.PNG)

Now the code:

![Annotation 2020-09-09 100514](https://user-images.githubusercontent.com/6702796/92571960-116a3780-f284-11ea-91d0-b9c79166f03b.png)

### Steps to reproduce
Define a b-field
set labelPosition property to 'on-border' and position property to 'is-right'.

### Expected behavior
The label of the b-field should be aligned to right as the field itself does.

**Comment by jtommy** [comment]
@bcourteaud please open a new issue
