### ISSUE TITLE
Make tabs buttons NOT anchors - a11y focus issue

### ISSUE THREAD

**Issue by jq-87** [buefy/buefy#2602]
**Buefy** version: [0.8.20]

### Description
Tabs are not focusable.
Tabs are currently using anchor tags which is not correct.
Tabs should be buttons.

The following is a related issue, but I am creating this issue because it is more specific and hopefully is something that can be addressed quickly:
https://github.com/buefy/buefy/issues/576

### Steps to reproduce
Try to use your keyboard or a screen reader to navigate tabs - you can not.

### Expected behavior
Tabs be focusable elements. This can be fixed by using buttons instead of anchors with no href.

### Actual behavior
Buefy tabs are not focusable.

For reference here is a suggested implementation of tabs:
https://www.w3.org/TR/wai-aria-practices/examples/tabs/tabs-1/tabs.html

**Comment by service-paradis** [comment]
There is a PR opened in Bulma since 2018 about this:
https://github.com/jgthms/bulma/pull/2003

**Comment by Muhnad** [comment]
Hey! 

I just need to say something about the solution you show by replacing the links with buttons to solve the issue.

the issue with the tab component here is not related by links it's all about bad implementation. I need to dig more into the component to figure out why links in not focusable but I think the implementation using `onClick` event on `<li>` to make the transition.

My Point is the tab component could be implemented by using Links or Buttons the both are correct but using Links is correct and it works in situations better than buttons.
by using Links and linking the links with sections, that improve accessibility by making sure the components will work even if the JS not found.

**Comment by Muhnad** [comment]
the focus issue is happening because of `href` attribute is missing. [Focusable elements in HTML spec](https://html.spec.whatwg.org/multipage/interaction.html#focusable) 
I suggest new enhancements in the tab component that will make the tab components focusable and more accessible.

if the PR merged then this buefy team should update the tab component and implement the new roles and attributes and make the tab components accessible for both screen-readers and keyboard users.

**Comment by service-paradis** [comment]
I created a PR with a11y improvements for tabs (#2744). Would love to have some feedback on it!
