### ISSUE TITLE
Sidebar slides to middle of page and disappears when closed/cancelled but "open" property locked to "true" in parent

### ISSUE THREAD

**Issue by richardboydnz** [buefy/buefy#2612]
### Overview of the problem

**Buefy** version :buefy@0.8.20
**Vuejs** version: vue@2.6.11
**OS/Browser**: Chrome + Firefox

### Description

The b-sidebar `open` property depends on a property in the parent. When sidebar tries to close itself (sets internal `isOpen` to false through Close and/or Cancel) but parent locks `open` property to `true`), it tries to animate a close, but position is not set correctly so it slides to the middle of the screen before it disappears. Internal attribute `isOpen` is now `false` while property `open` is `true`.  As the parent thinks that it is still open, it can not open it again.

### Steps to reproduce
- `<b-sidebar open="true">`
- press `Esc` to cancel sidebar

for a practical example I used:
     `<b-sidebar type="is-light" fullheight right :open.sync="open">`
     which malfunctions if the `open` setter does not successfully change the property to false

### Expected behavior

If the computed value of `open` stays `true` after an attempt to change it to false - it should stay open. 

If the desired behaviour is to close it anyway, it should just close properly and not do an ugly slide to the middle of the screen.

### Actual behavior

1) Sidebar slides to the middle of the screen
2) disappears
3) it is impossible to open the sidebar again

**Comment by service-paradis** [comment]
Can you reproduce it on Codepen?

**Comment by apa14** [comment]
Hi, I'm having this problem or at least one that is too similar. I create a project to show you more info about what is happening.
https://github.com/apa14/buefy-sidebar-error
My problem is that i change sidebar open variable state with events but when is open and i click out of the sidebar the sidebar disappear with no reason because his close event is called automatically.

Can you take a look pls?

**Comment by michaelcaterisano** [comment]
Same issue here. Sidebar is ignoring `open` property set to true and closing when clicking outside of sidebar area.

**Comment by sorencc** [comment]
I am also having this problem. In short it's misleading that when the `:active` prop does not have `.sync` appended the cart still closes without the prop being updated. This causes the prop and the actual open state to get out of sync. I have a bit of custom logic and don't want to always close the bar when someone clicks elements outside of it. 

Example -
https://codepen.io/sorencc/pen/bGwrBOM

For anyone else struggling with this the work-around for the moment is to set `:canCancel="[]" :overlay="false"` and just facilitate your own overlay. The z-index for the `sidebar-content` is 41.

**Comment by michaelcaterisano** [comment]
Hi @sorencc. I'm not sure, but I think this is because the `<b-sidebar>` fires a `close` event when the user clicks outside of the sidebar, which seems to internally set its `open` value to false. I've added a function on the `@close` event to your codepen here to demonstrate: https://codepen.io/michaelcaterisano/pen/ExgvZvg

I had a simliar problem that I wrote about on #3101, summary below:

Sidebar fires 'close' event is fired when last item of array is removed. https://codepen.io/michaelcaterisano/pen/YzGQVaZ

I'm dynamically rendering elements in the sidebar from an array. On item click, item is removed. When the item index === array.length - 1, the sidebar fires the 'close' event, which closes the sidebar.

Buefy version: 0.9.4
Vuejs version: 2.6.11
Browser: Chrome

Steps to reproduce

Click "open sidebar". The sidebar opens.
Click item in sidebar to remove it. Item is removed.
Click the last item in the list. Sidebar fires 'close' event and closes.
Expected behavior: Sidebar stays open, does not fire 'close' event when item inside of sidebar is clicked.

Actual behavior: Sidebar fires 'close' event when item index === array.length - 1.

**Comment by sorencc** [comment]
Hey @michaelcaterisano! Yeah that is indeed the issue. I was also using the @close callback until I realized that it was really operating as a callback rather than a handler, and that the internal state was getting out of sync as a result. 

My underlying suggestion is just that this should actually be a controlled component and not have that duplicitive internal state. The `@close` prop should behave as a handler for the events and let the user facilitate the closing themselves, rather than a callback that's fired after the fact.

I think it's a much more common sense contract that if the `open` prop doesn't have `.sync`, then the opening and closing needs to be facilitated by the parent component, rather than needing the caveat that the value of the `open` prop doesn't actually directly determine whether the sidebar is open or closed.

**Comment by michaelcaterisano** [comment]
Just to clarify the language here, my understanding is that `@close` is an event listener, equivalent to `v-on:close`, to which an event handler function is assigned, like `@close=handleCloseEvent`. `@close` itself is neither a callback nor a handler function.

But I agree that managing `b-sidebar`'s internal state is tricky. Opening the sidebar with a button click and setting a variable `isOpen` to true and setting `b-sidebar`'s `open` prop to `isOpen` works well enough, but the only way I found to manage the sidebar closing was to manually set `isOpen` to `false` on the sidebar `@close` event. This seems to keep things in sync.

**Comment by sorencc** [comment]
Sorry been meaning to say `:on-cancel`. But yeah I'm referring to the values that are passed to those props not the props themselves.
Either way, what you're saying about those props taking handlers not callbacks is what I'm suggesting. Currently both function more as a callbacks since there are un-preventable default behaviors baked into the sidebar component. 

At least `:on-cancel` is accurately described as a callback rather than a handler in the documentation. :shrug: https://buefy.org/documentation/sidebar/#api-view

**Comment by apa14** [comment]
Hi both of you, ty for the support and the ideas. Even that, I don't have a clearly idea of how to solve the problem, how i can prevent the sidebar send close event when click out in any part of the page?? Just adding :on-cancel prop is enough to change the 'normal' behavior of the sidebar??
Otherwise I thought that this is a mistake of the component and should be solved.

**Comment by sorencc** [comment]
Hey @apa14 as I mentioned in my initial comment

> For anyone else struggling with this the work-around for the moment is to set :canCancel="[]" :overlay="false" and just facilitate your own overlay.

Example https://codepen.io/sorencc/pen/qBaPRKr

**Comment by apa14** [comment]
Thanks @sorencc, in my project was enough with `:can-cancel="[]" `prop. I don't need to set the overlay to false cause I use a button to hide/show the menu so its ok.
I really appreciate your help mate :)
