### ISSUE TITLE
Dynamic column visibility breaks on empty searchable tables

### ISSUE THREAD

**Issue by tecaz** [buefy/buefy#2613]
### Overview of the problem

**Buefy** version: 0.8.20
**Vuejs** version: 2.6.11
**OS/Browser**: any

### Description

When defining a column filter (via the `searchable` prop on `BTableColumn`) that causes the table to become empty, dynamic column visibility (ie the `visibility` prop) stops working.

### Steps to reproduce

See [https://codepen.io/tecaz/pen/BajWWqZ](https://codepen.io/tecaz/pen/BajWWqZ)

**Comment by jtommy** [comment]
You are right, but probably it will be fixed in the next breaking version 0.9.0

**Comment by BALOTIAS** [comment]
This is really annoying, I'm working on a side project in which I use buefy and I'm really happy with it, but this destroys the whole project, since the main feature to search for items, and this breaks the table every now and then.

![annoying-table](https://user-images.githubusercontent.com/13562297/87220071-395f1c80-c361-11ea-8fa9-a3e44753be76.JPG)

**Comment by BALOTIAS** [comment]
So I digged a bit through the source code and I've found out that this happens due to the TableColumn in the header not being destroyed in **TableColumn.vue:78/79**. 

If I comment them out everything works fine again. I didn't create a PR since I'm not sure why these checks are there and what side effects this could have, but I hope this can help you fix this sooner @jtommy  :))

```javascript
beforeDestroy() {
    // if (!this.$parent.visibleData.length) return
    // if (this.$parent.newColumns.length !== 1) return
    if (this.$parent.newColumns.length) {
        const index = this.$parent.newColumns
            .map((column) => column.newKey)
            .indexOf(this.newKey)
        if (index >= 0) {
            this.$parent.newColumns.splice(index, 1)
        }
    }
}
```

The simplest way to test this is in the documentation example **ExToggleColumns.vue** by adding two buttons, one which clears the temporary data array of the table and one that fills it out again with **tableDataSimple** and play around with the checkboxes and toggling the data.

**Comment by jtommy** [comment]
@BALOTIAS take a look at 0.9.0 branch
