### ISSUE TITLE
Creating multi-level nested dropdown

### ISSUE THREAD

**Issue by imfaisalkh** [buefy/buefy#2620]
I'm using **Buefy** library for creating UI elements. If I want to create a drop-down menu, it is fairly simply: https://buefy.org/documentation/dropdown

However, there are no examples of creating a multi-level drop-down menu using buefy components. I've tried different approaches but I'm unable to do so.

If anyone can help me in this regard, that would be appreciated.

**Comment by jtommy** [comment]
It's no possible at the moment and unfortunately it isn't in the roadmap

**Comment by douglasg14b** [comment]
Well, that sucks. Still the biggest thing that makes me avoid a framework due to the common use-case of nested data :(

Kinda sucks that it can't stay open as a feature request?

**Comment by jtommy** [comment]
@douglasg14b would you like work on it ? I would happy to see a PR to review 😉

**Comment by douglasg14b** [comment]
Nope! 

Was just checking in on some libraries after a couple years to try and switch things up, that's just on my requirements list.

No way am I gonna develop multi level dropdowns for every Vue component library I've considered. I more commented because the issue was closed, which typically means it will never be considered.

Thanks for asking though!
