### ISSUE TITLE
Can I custom/hide pagination button?

### ISSUE THREAD

**Issue by biigpongsatorn** [buefy/buefy#2657]
### Description
Can I hide or custom UI of the pagination button?

![image](https://user-images.githubusercontent.com/10693658/86808861-70a1a500-c0a5-11ea-9958-3d1d6bdb4e6e.png)

**Comment by jtommy** [comment]
@biigpongsatorn next version you can pass a slot, at the moment you have to set `paginated`=false

**Comment by unikitty37** [comment]
Was this implemented? I still can't see anything about how to do it in the docs, and the only solution I can find for adding "jump to page" is in #1015, which suggests putting it in the `bottom-left` slot — the problem is that this puts pagination functionality in two separate places, which is ugly.

Ideally I'd be able to click on the blue "current page" field to turn it into a text field where I could enter a page number.

**Comment by jtommy** [comment]
You should be able to pass a slot called `pagination`

**Comment by unikitty37** [comment]
Brilliant, thanks — it doesn't seem to be mentioned in the list of slots on https://buefy.org/documentation/table#api-view, though 🙂

**Comment by jtommy** [comment]
You can make a PR
