### ISSUE TITLE
Console errors from TagInput when adding tags in a certain order

### ISSUE THREAD

**Issue by Thaurin** [buefy/buefy#2673]
### Overview of the problem

**Buefy** version: [0.8.20]
**Vuejs** version: [2.6.11]
**OS/Browser**: Windows 10/Chrome 83.0.4103.116

### Description

Using an array of integers as data prop in the TagInput component, adding tags in a certain order seems to produce "Duplicate keys detected" Vue warnings in the console, specifically when the second tag added is the one before the first added.

### Steps to reproduce

1. Create a TagInput with an array as data
2. Select second tag
3. Select first tag
5. Look at the console to see the Vue warnings

### Expected behavior

No errors should be reported on the console.

### Actual behavior

The console reports the following Vue warnings:

    [Vue warn]: Duplicate keys detected: '4'. This may cause an update error.
    [Vue warn]: Duplicate keys detected: '4'. This may cause an update error.
    [Vue warn]: Duplicate keys detected: '4'. This may cause an update error.
    [Vue warn]: Duplicate keys detected: '4'. This may cause an update error.

This behavior can be reproduced [in this CodeSandbox](https://codesandbox.io/s/buefy-template-w3tzw?file=/src/main.js).

**Comment by Zephyrrus** [comment]
I experienced the same issue when my tags were integers. 

The problem is caused by https://github.com/buefy/buefy/blob/dev/src/components/taginput/Taginput.vue#L11 when the tags are integers and not strings.
In your example, the first key is calculated like `2+0`, where the `2` is the value from your tag, and the `0` is the index, and the second key is calculated like s`1+1`, where the first `1` is tag's value and second `1` is the index.

One solution would be to change `getNormalizedTagText` so it always returns a string

**Comment by Thaurin** [comment]
I've just switched the tags to strings for now to get around this.
