### ISSUE TITLE
BTable no longer updates the "currentPage" prop

### ISSUE THREAD

**Issue by tecaz** [buefy/buefy#2771]
### Overview of the problem

**Buefy** version: [0.9.1]
**Vuejs** version: [2.6.11]
**OS/Browser**: any

### Description

The `currentPage` prop of `BTable` is no longer updated when the page changes.

### Steps to reproduce

[Minimal working example](https://codepen.io/tecaz/pen/XWdjJJM)

**Comment by jtommy** [comment]
My bad! I removed the support to this prop .sync before in the next breaking i'm going to replace all with v-model so you should listen `page-change` event.
I'll clean docs and changelog, thanks

**Comment by Tofandel** [comment]
@jtommy While I agree that changing .sync to v-model where possible is a very good idea and good practice, why the change for all the other ones? .sync is just syntactic sugar for `:prop="value" @updated:prop="(v) => value = v"`
So why make our job more complicated when vue provides a simple API that's not going anywhere soon for that already?
That means now we need to write
`:currentPage="currentPage" @page-changed="(v) => currentPage = v"`
When before it was just
`:currentPage.sync="currentPage"`

**Comment by jtommy** [comment]
Do you really need it if there is already an event?

**Comment by Tofandel** [comment]
Example use case: saving the current page into the database so that when you reload the page you are on the same page

You need to give the page to the component and receive it when it changes, exactly what .sync is very known for, It basically just gives you a naming convention for events so you don't have to search for the right event name everytime you need one in the documentation
Eg:
`$emit('updated:currentPage', currentPage)`

**Comment by jtommy** [comment]
You're right but in order to support two version (vue 2 and vue3) without have two codebase i thought to remove .sync support if i can

**Comment by Tofandel** [comment]
@jtommy I see, you are preparing for vue3, they are deprecating .sync just because now you have multiple v-model support but they are not removing it
So
```
:current-page.sync="currentPage"
```
Becomes
```
v-model:current-page="currentPage"
```
But they are not removing it, just a syntax change, so that means that the events named `updated:currentPage` will work with the future `v-model:current-page="currentPage"` I think that's kinda better regarding vue 3 support

**Comment by lgarczyn** [comment]
v-model doesn't work either, b-table emits `page-change`, not `change`, which is required for v-model

I absolutely love this platform, but if you want to force people to give up a valid vue 2 feature, please make sure things still work with the alternative.

**Comment by jtommy** [comment]
You have to use `page-change` event

**Comment by lgarczyn** [comment]
So to check, v-model won't be added for page-change? I'm really not sure what's the point of removing features, you can just send events for .sync and v-model:page-change to support both vue 2 and vue 3

**Comment by jtommy** [comment]
It has been restored, next release will be available

**Comment by lgarczyn** [comment]
I need to add that b-table uses `update:openedDetailed` instead of the standard `update:opened-detailed`.

All events should strictly use burger-case

**Comment by lgarczyn** [comment]
Another note, `update:openedDetailed` uses camelcase instead of the standard burger-case for events
