### ISSUE TITLE
Autocomplete: slot for group header

### ISSUE THREAD

**Issue by rubjo** [buefy/buefy#2800]
### Description

Provide a slot for customising autocomplete group header output

### Why Buefy need this feature

To make it easier to eg. have localised headers, or headers with other classes than `.has-text-weight-bold`

**Comment by rubjo** [comment]
Hm, looked in the source, and it seems you have already thought about that 👍

**Comment by jtommy** [comment]
I'll add in the docs, or you can make a PR ;)

**Comment by thefoxie** [comment]
All of this is really nice, but in my usecase I want to be able to work and select whole group. I found out the group won't get rendered when the group is empty.

these lines are responsible: https://github.com/buefy/buefy/blob/da5692d0f4e47c6d883a50ec9a2e8a96093a0b06/src/components/autocomplete/Autocomplete.vue#L177-L180

Those few lines are really useless, because this feature is not consistent. When I pass more than one group + the other group has got items, the empty group is rendered as well. Even when I add an #empty slot, the group is in. 
![obrázok](https://user-images.githubusercontent.com/15309350/92943984-b5eea400-f453-11ea-94f5-7a408eea4c75.png)

**Comment by jtommy** [comment]
@thefoxie how did you do ? The code should be ok because it shows empty slot only there aren't groups with at least one element

**Comment by thefoxie** [comment]
@jtommy yeah and it's still showing the empty group, which I want but I want to show it even without the empty slot. The autocomplete shows the empty group in every situation except the case when there's only one group that is empty (without items). The lines mentioned above are responsible. The computedData returns even empty group (I want this in my case, but I guess this is not intended). And there's one more thing. The group slot exposes only one field and it's index. I'd need an ID of the object/group as well, as it's there already...without it I need to find it via index which is...waste of resources.

```vue
 <b-autocomplete
        v-model="autocomplete"
        icon="magnify"
        :placeholder="placeholder"
        :open-on-focus="true"
        :data="filteredData"
        field="name"
        :clearable="true"
        group-field="name"
        group-options="subcategories"
        @select="selectOption($event)"
        @typing="getFilteredTags($event, 'name')"
    >
        <template #group="category">
            <a class="dropdown-item" @click="logme(category)"
                ><strong>{{ category.group }}</strong></a
            >
        </template>
        <template #default="props">
           <span style="padding-left: 1rem;">
                {{ props.option.name }}
            </span>
        </template>
        <template #empty>No results for</template>
</b-autocomplete>
```

**Comment by jtommy** [comment]
Please create a codepen or similar, don't post only part of your code, thanks

**Comment by thefoxie** [comment]
Here it is.

Type in `vs` to get the prediction/suggestion of the empty group. It works when empty is present.
With empty template:
https://codepen.io/thefoxie/pen/dyMqWNv

Without:
https://codepen.io/thefoxie/pen/abNaWLZ
