### ISSUE TITLE
Taginput with Autocomplete: pass taginput’s confirm-keys prop to autocomplete

### ISSUE THREAD

**Issue by rubjo** [buefy/buefy#2871]
### Description

Scenario: multiple tag inputs with open-on-focus autocompletes, where each input typically will contain more than one tag

Problem: Keyboard-only navigation becomes complicated, as both enter and tab will select the highlighted option (and tab will additionally move to the next field)

Solution: new prop allowing taginput to not add tag on tab (leaving enter = select, tab = move to next field)

**Comment by service-paradis** [comment]
The issue here is taginput does not respect the prop `confirm-keys` when using autocomplete.

My suggestion for this would be to add a prop for autocomplete to choose which keys we want to use to select an item. This way, from taginput, we could pass `confirm-keys` prop to the autocomplete component.

**Comment by jtommy** [comment]
@service-paradis It's no a bad idea 👍

**Comment by rubjo** [comment]
I didn’t even notice the `confirm-keys` prop until now. Sounds like the logical and elegant solution, @service-paradis.

If one of you don’t submit a PR for it, I might have a look at it within the next few days.
