### ISSUE TITLE
Dropdown does not reposition automatically

### ISSUE THREAD

**Issue by diazod** [buefy/buefy#2965]
### Versions

**Buefy** version: v0.9.3
**OS/Browser**: Chrome 85.0.4183.121 (Official Build) (64-bit)

### Description
When activating the dropdown button is in the bottom edge of the visible area of the screen the menu appears outside of view.

### Steps to reproduce

![FJbC5cuJhC](https://user-images.githubusercontent.com/474672/95569774-52da3800-0a26-11eb-9017-1492dc0f683f.gif)

### Expected behavior

![o1CWD3NeVv](https://user-images.githubusercontent.com/474672/95570031-a8164980-0a26-11eb-834c-83e8e778774d.gif)

### Actual behavior

The dropdown menu appears outside of the visible area of the screen

**Comment by yuchaosydney** [comment]
When scroll down the page and the button reached the bottom of the page, that "arrow down" icon in button becomes "arrow up", which results an illusion that dropdown should show up above the button.

**Comment by yuchaosydney** [comment]
@diazod in terms of dropdown positioning, buefy behaves in the same way that Bulma does.

This can easily verified by reproducing the issue on [official bulma dropdown document](https://bulma.io/documentation/components/dropdown/) :

![bulma-demo-1](https://user-images.githubusercontent.com/5698884/96306607-b7f7e400-104b-11eb-97b4-760997c947e5.gif)

The "Expected behaviour" is actually from [bootstrap dropdown page](https://getbootstrap.com/docs/4.0/components/dropdowns/#single-button-dropdowns).

Therefore, this should not be a buefy issue as it is consistent with Bulma dropdown behaviour.

**However**, according to [official document](https://bulma.io/documentation/components/dropdown/), Bulma does support opening up dropdown list on top of the button being clicked:

![bulma-demo-3](https://user-images.githubusercontent.com/5698884/96307438-589ad380-104d-11eb-9419-2abf86f4e4ba.gif)

Probably you should find a workaround with this feature offered by Bulma.

Hopefully, this helps :)

**Comment by diazod** [comment]
Well it gives me clarity why won't be changed:

For what I tell me it's an inconvenient behaviour in the core of `Bulma` that cannot be fixed from your side, in my opinion it's unfortunate that the shortcomings need to be patched by the developer using the library.

Thanks for the information, I'll close the issue as this won't be fixed

**Comment by yuchaosydney** [comment]
Hi @diazod , thanks for your message. 

I agree with you that this shortcoming is inconvenient and fixing this issue in buefy level would be handy. (In my last comment, I think this "should not" be a buefy issue only because it behaves consistently with Bulma)

I am not sure should buefy include a fix for this in future road map. Maybe @jtommy would be able to better answer this :)

**Comment by jtommy** [comment]
It's no primary but I might apply the same approach of autocomplete component

**Comment by Heliodromel** [comment]
Hi, do you guys have any news about this issue in Bulma ?
