### ISSUE TITLE
Autocomplete closes Sidebar when any of the option is selected.

### ISSUE THREAD

**Issue by bhushan** [buefy/buefy#3052]
If i want to use autocomplete on Sidebar then .. when i select any of the options from AutoComplete it closes Sidebar. 

**Possible Cause:** 

AutoComplete fires few events when we select any of the option and may be it makes Sidebar loose the focus so it closes automatically.

**Comment by jtommy** [comment]
Are you using `append-to-body` prop ?

**Comment by bhushan** [comment]
No .. I have just used v-model and data property

**Comment by jtommy** [comment]
Can you reproduce on codepen or similar?

**Comment by elmatou** [comment]
I had a similar issue (autocomplete in dropdown).

I can confirm `append-to-body` solved the issue by narrowing (to nothing) the event bubbling. could be in docs.

**Comment by bhushan** [comment]
@elmatou did you used `append-to-body` as a property on autocomplete?

**Comment by elmatou** [comment]
Yep !
```
        <b-autocomplete
         ...
          append-to-body
        >
```
and it woks well in main cases. I did however have some trouble with some z-index stacking.

**Comment by bhushan** [comment]
Ok this needs to be closed then

**Comment by elmatou** [comment]
not sure. the propagation issue is still there, let @jtommy decides.
as `append-to-body` didn't do well in my case, I did find a better workaround by stopping the propagation on the click event.
```
        <b-autocomplete
          ...
          @select="
            (data, e) => {
              e.stopPropagation();
              this.selectedData = data;
            }
          "
        >
```
It now works perfectly, and I'm pretty sure this is the desired behavior, maybe I can submit a patch to the lib. Just say it.

**Comment by jtommy** [comment]
I should think about it, your idea is correct but I would like to find a global solution.
In the meanwhile you can create a PR 😃

**Comment by elmatou** [comment]
I was thinking of some thing like:
```
setSelected(option, closeDropdown = true, event = undefined) {
            if (event) event.stopPropagation()
           ...
           }
```

But I did saw some issues with other components too.
What was the first intent with `append-to-body` ?

**Comment by jtommy** [comment]
@elmatou fix issue using dropdown (datepicker, autocomplete, ecc) when they are into a particular wrapper (modal, table, ..)

**Comment by OrestHk** [comment]
Hello,

Sorry to dig out this issue, but the problem seems to still be here
Looking a bit into the sources of the Sidebar.vue component, it seems like the following function is not working as expected : 
```
        getWhiteList() {
            const whiteList = []
            whiteList.push(this.$refs.sidebarContent)
            // Add all chidren from dropdown
            if (this.$refs.sidebarContent !== undefined) {
                const children = this.$refs.sidebarContent.querySelectorAll('*')
                for (const child of children) {
                    whiteList.push(child)
                }
            }
            return whiteList
        },
```
The problem seems to be linked with "dynamic" elements, for instance the clear button in an autocomplete, or an option in an autocomplete. But I guess that it can be extended to either element that is deleted from the DOM (not just hidden through CSS)

For exemple when you are clicking on the clear button of the b-autocomplete element, it disappear from the DOM as the click event is bubbling, by the time the getWhiteList function is reached, the element is no longer in the list of childrens, which will make the last condition in the following function to return true, and by doing so, close the sidebar
```
        // Also issued from Sidebar.vue
        clickedOutside(event) {
            if (this.isFixed) {
                if (this.isOpen && !this.animating) {
                    const target = isCustomElement(this) ? event.composedPath()[0] : event.target
                    if (this.getWhiteList().indexOf(target) < 0) {
                        this.cancel('outside')
                    }
                }
            }
        },
``` 

One of the solution could be to stop the propagation for the click on those elements, tried it, seems to work for those particular cases (clear button / autocomplete option)
But I don't know if the bubbling is necessary elsewhere !
I'll try to continue to dig it, but here's the information if it can help !
