### ISSUE TITLE
Sidebar closes when last item in array is removed

### ISSUE THREAD

**Issue by michaelcaterisano** [buefy/buefy#3101]
Sidebar fires 'close' event is fired when last item of array is removed. https://codepen.io/michaelcaterisano/pen/YzGQVaZ

I'm dynamically rendering elements in the sidebar from an array. On item click, item is removed. When the item index === array.length - 1, the sidebar fires the 'close' event, which closes the sidebar. 

Buefy version: 0.9.4
Vuejs version: 2.6.11
Browser: Chrome

 Steps to reproduce

1. Click "open sidebar". The sidebar opens.
2. Click item in sidebar to remove it. Item is removed.
3. Click the last item in the list. Sidebar fires 'close' event and closes.

Expected behavior: Sidebar stays open, does not fire 'close' event when item inside of sidebar is clicked.

Actual behavior: Sidebar fires 'close' event when item index === array.length - 1.

**Comment by sorencc** [comment]
Hey @michaelcaterisano! Checking this out since you linked it from the other issue I commented on. I was also experiencing my own version of this issue and the underlying bug seems to be that for whatever reason in some circumstances, like yours, the click event propagates up to an element outside of the sidebar which then fires the close event. Adding `.stop` to your `@click` prop on the items is an easy workaround for the time being. ie `@click.stop="remove(index)`.

**Comment by michaelcaterisano** [comment]
This totally works, thanks @sorencc! I agree at this seems like a bug, possible related this fix? #2917?
