### ISSUE TITLE
Importing individual components / Tree-Shaking

### ISSUE THREAD

**Issue by schmod** [buefy/buefy#338]
The current full build of Buefy is quite large (~300kb), and it does not currently appear to be possible (or at least straightforward) to use individual Buefy components without importing the entire library.

---

On a (very) preliminary investigation, I noted three underlying causes:

* There are no standard conventions for consuming 3rd-party `.Vue` files with Webpack or other tools, which makes it difficult/impractical to directly import buefy's unbuilt sources a la `import Checkbox from 'buefy/src/components/checkbox`.
  * Many build configurations do not run `node_modules` through preprocessors, nor are they necessarily set up to deal with the quirks of each and every 3rd-party library being used.
* Buefy is built and distributed as a single `.js` file.  While this enables the library to be loaded via a single `<script>` tag, it prevents lodash-style imports a la `require('buefy/checkbox')`.  
* [`index.js`](https://github.com/rafaelpimpa/buefy/blob/2edac0816712855e3d1eb74a26aa9e130e3face9/src/index.js) loops through each component, and registers it with Vue.  Even if we were able to use ES modules (`import { checkbox } from 'buefy'`), this loop creates hard references to each component, making it impossible for tree-shaking to drop any unused components.  

I'm not sure what approach we'd want to take to enable us to allow Webpack/Browserify users to  import only the Buefy components that they need, but wanted to get this documented and start a discussion.

I'm still somewhat new to the Vue community.  I'd appreciate any pointers toward other libraries that have dealt with this issue.

**Comment by jtommy** [comment]
I'm sorry... my mistake about number of issue 😅

**Comment by richgoldmd** [comment]
I attempted this be rewriting index.js to include only the injected components, and the rest would have to be imported explicitly. 

Doing so resulted in a savings in the final bundles of about 90kb in a production build, which is about half the size of the minimized index.js in the distro (without explicitly including any components). (I extract CSS in my build so that is not included)

Savings may be greater if the injected items were excluded also, but for my purposes, this difference isnt enough to justify maintaining a custom copy of the codebase.

**Comment by VickyKoblinski** [comment]
This is a feature me and my team are very interested in and is preventing us from using Buefy at this time (we sadly just pulled it from the project). We'll be keeping an eye on this!

**Comment by ksr583** [comment]
+1 for this!

**Comment by katonada** [comment]
You have the nice solution by **throrin19** (on the middle of the page) that works for importing single components https://github.com/buefy/buefy/issues/458.
Not native but cool hack :)

**Comment by jtommy** [comment]
@katonada As you can see we're working about it https://github.com/buefy/buefy/pull/826. We think it will ready in the next release.

**Comment by katonada** [comment]
@jtommy Great! I didn't notice in pull requests 
👍 👍 👍

**Comment by vladkosarev** [comment]
Also would love this. Have to go to raw bulma for now because of library size.

**Comment by lukenofurther** [comment]
I see Beufy still hasn't adopted an explicit approach to imports. I won't be using it, which is a shame as it looks very good.

**Comment by jtommy** [comment]
@lukenofurther what do you mean ?

**Comment by lukenofurther** [comment]
@jtommy actually I just found out it is possible, apologies. You must ensure .vue files in node_modules aren't excluded from babel processing (my build was excluding them) and you need to import the relevent src file. So you can do it like this:

```vue
<template>
  <BTag type="is-primary">It works</BTag>
</template>

<script>
import { BTag } from 'buefy/src/components/tag'

export default {
  name: 'MyComponent',
  components: {
    BTag
  }
}
</script> 
```

If you do this then you don't need to register globally with `Vue.use(Buefy)` or `Vue.use(Table)` as suggested in the start guide. Personally I prefer this way of importing external dependencies as it makes dependencies more explicit.

I didn't see this method of use in the documentation anywhere.

I haven't tested this in an SSR environment. I notice that the src component files themselves call `Vue.use` but this depends on the window object being present.

**Comment by amir20** [comment]
@lukenofurther This is documented https://buefy.org/documentation/start under "Individual components as Vue plugins".

**Comment by lukenofurther** [comment]
@amir20 that's a different type of usage. The way I set out above registers the component locally in the component that uses it, as you would any other component, rather than as a global plugin.

**Comment by jtommy** [comment]
@lukenofurther if you want import only the pure component you can use `import { BTaginput } from 'buefy/dist/esm/taginput'`

**Comment by seyfer** [comment]
@jtommy 
`import BPagination from 'buefy/dist/esm/pagination';`
doesn't wok with Vue render function. We use **pure Vue render functions** and we do not want to use `Vue.use(Pagination)`

`h(BPagination, {})`;

`import BPagination from 'buefy/src/components/pagination/Pagination.vue';`
does work with the render function.

@lukenofurther approach for importing from `/src` works for us. Still feels wrong to import from `/src`. Would be great to have another way.

**Comment by jtommy** [comment]
@seyfer because you'are wrong.. Buefy exports the components as Vue plugin using `import { Pagination } from 'buefy'` but you can import the only components using `import { BPagination } from 'buefy/dist/esm/pagination'`

**Comment by seyfer** [comment]
@jtommy true, it works! my mistake was not using `{}` on import. thanks.

**Comment by seyfer** [comment]
@jtommy hey, I would like to clarify one moment, why I thought initially that importing from `/src` was better for our use-case and would like to ask if there are serious reasons to not keep doing it?

We used that approach because of the fact, that we use only Vue render functions, no templates at all.
And if component imported from `/src` we get just component and we can use it in the render function, as
```
import { BDropdownItem } from 'buefy/src/components/dropdown/Dropdown';
//later in render function
return h(BDropdown, {}, options);
```

When imported from `/dist/esm` it also works, but we have noticed that every component additionally registers itself as a Vue plugin, so if we do 
```
import { BDropdown, BDropdownItem } from 'buefy/dist/esm/dropdown';
```
the _buefy/dist/esm/dropdown_ file has this code inside
```
import { D as Dropdown, a as DropdownItem } from './chunk-4d76806f.js';
export { D as BDropdown, a as BDropdownItem } from './chunk-4d76806f.js';

var Plugin = {
  install: function install(Vue) {
    registerComponent(Vue, Dropdown);
    registerComponent(Vue, DropdownItem);
  }
};
use(Plugin);

export default Plugin;
```

which does something completely not needed in the pure functional app with render functions. 
still, we have changed all our imports to use `dist/esm` with some questions left.
1. what would be the biggest downside if we keep using `/src` imports? I see the following
  - longer build because ts/babel needs to process imported files from `node_modules`
  - problems with tree shaking in webpack?
  - unexpected problems if our setup is not compatible with some new js features used in `/src` code on some update, so it will not build for us.
2. is it possible maybe to consider needs for people using FP approach and include another folder in the build, something like
`dist/esm/fp` or just `dist/fp` which will allow importing individual components as from `/dist/esm` _but without registering them as a plugin_? :) might be a good idea?

**Comment by jtommy** [comment]
There isn't a downside but importing a component from src your builder might throw errors (lint for example).

I don't understand the second point. If your project supports three shaking will remove all not used parts and so the Vue plugin because your importing the component (BDropdown instead of Dropdown)

**Comment by seyfer** [comment]
@jtommy ok I think I got it. you mean because of this direct export
`export { D as BDropdown, a as BDropdownItem } from './chunk-4d76806f.js';`
all the code with the Plugin registration below will not be executed. 
Thank you for the explanation!
