### ISSUE TITLE
render(createElement, context) functions break in @vue/compat

### ISSUE THREAD

**Issue by tgrushka** [buefy/buefy#3457]
### Overview of the problem

**Buefy** version: 1.0.0
**Vuejs** version: @vue/compat MODE=2
**OS/Browser**: any

### Description

Vue 3 has removed the createElement argument from render() and made it global as h().
See docs:
https://v3.vuejs.org/guide/migration/render-function-api.html

Trying to get on an upgrade path from Vue 2 to 3 using @vue/compat MODE = 2.

The Vue team says that Buefy is basically not using the render function correctly, because it has 2 arguments:
`render(createElement, context)`
which causes @vue/compat to think the function is already wrapped for Vue 3.

Vue team says (emphasis mine):
> Because in Vue 2, render functions __don't have a second argument__

https://github.com/vuejs/vue-next/issues/4298

In other words, Buefy is using render(createElement, ...) "incorrectly" in several places by having a second argument at all.

### Steps to reproduce

1. Alias vue to @vue/compat in build, setting mode: 2 to put in Vue 2 compatibility mode
2. Builds without errors or warnings related to this particular issue.
3. Raises error in the browser:
```
Uncaught TypeError: createElement is not a function
```

### Expected behavior

Buefy should build with warnings related to use of render(createElement) and run successfully in @vue/compat with mode = 2.

Buefy should only use one argument (createElement) in its render calls.

### Actual behavior

Buefy builds with warnings unrelated to this issue and crashes in the browser due to the use of 2 arguments in render calls, rendering it totally incompatible with @vue/compat mode 2.

**Comment by LinusBorg** [comment]
To give a little more context: `@vue/compat` can support Vue 2 render function. But as the function signatures for `render` and `h`/`createElement` differ, we have to actively detect wether a render function has been compiled with the Vue 2 or Vue 3 renderer, and do so in a performant way since this happens at runtime.

For stateful components, we can do this by checking the length of the arguments of the render function, since:

* Vue 2 render functions (of stateful components) only receive one argument (`createElement`)
* Vue 3 render functions (when compiled from an SFC template) receive at least 2: `_ctx` and `_cache` 

So if a render function has 2 or more arguments, it must have been compiled with the Vue 3 compiler and we can skip some work we would otherwise do to wrap it.

The problem with Buefy here is that at least in some components, you have manually written render functions that accept a second (dead) argument:

https://github.com/buefy/buefy/blob/7dbe191761bcc169e895ac42817a403a2c038f6a/src/components/navbar/Navbar.vue#L243

**Comment by LinusBorg** [comment]
A more general note though: While removing the second `fn` argument here would solve the issue at hand, I would expect there to be more spots where incompatibilities could come up.

A brief scan through the codebase found this, for example:

https://github.com/buefy/buefy/blob/7dbe191761bcc169e895ac42817a403a2c038f6a/src/utils/helpers.js#L164

Where an internal property is used to check wether an object is a Vue component.

It's not uncommon for bigger libraries like buefy to reach for things like that in edge cases, so this is not meant as a critique. It's the reason we generally recommend for users of such libraries to wait for a Vue 3 compatible version.

**Comment by jtommy** [comment]
Thanks @LinusBorg
