### ISSUE TITLE
Circular progress bar

### ISSUE THREAD

**Issue by zhaojh329** [buefy/buefy#3547]
### Description

* To display the current progress of an operation flow.
* To display the percentage of some indexes.

![image](https://user-images.githubusercontent.com/28673295/135721448-741dd1fd-a026-4cf1-a56f-b2fdf6484229.png)
![image](https://user-images.githubusercontent.com/28673295/135721572-2ddbcf89-a83f-474f-89b4-aa134075c879.png)

**Comment by Mars073** [comment]
I added the feature on [a branch of my fork](https://github.com/Mars073/buefy/tree/feature/sc-3547%2Fcircular-progress-bar), the problem of the rounded version is that the data representation is not accurate and not easily correctable due to the limitations of SVG 2 (what I used), so in my opinion it would be necessary to use a canvas, but in this case it would be the accessibility which will lose in performances.

![image](https://user-images.githubusercontent.com/18756261/147992649-1c258b40-a251-4041-9628-eda992499b9a.png)
