### ISSUE TITLE
Dropdown with "hover" trigger incorrectly rendered on mobile devices 

### ISSUE THREAD

**Issue by glumb** [buefy/buefy#3961]
### Overview of the problem

**Buefy** version: v0.9.27
**Vuejs** version: 2.7.15
**OS/Browser**: MacOs/Chrome

### Description

The Dropdown does not render correctly in mobile view, when trigger 'hover' is set.
<img width="974" alt="image" src="https://github.com/buefy/buefy/assets/3062564/86aeeaa2-a1de-423a-b4af-b7b8c8b4d488">

### Steps to reproduce

1. visit https://buefy.org/documentation/dropdown on smartphone or desktop browser mobile emulation
2. tap "Hover me!"
3. see incorrect position and no background

### Expected behavior

Behave like the "Click me!" tiggered button

**Comment by kikuomax** [comment]
@glumb @wesdevpro You can test the new behavior here: <https://deploy-preview-3962--buefy-org.netlify.app/>

There are two drawbacks:
1. The dropdown won't be displayed on mobile screen unless triggers other than "hover" are enabled. But this should not matter on actual mobile (touch) devices because "hover" won't work on such devices anyway.
2. If "click" trigger is combined with "hover", the dropdown contents won't be closed by moving the pointer out of the trigger once users click on the trigger. This might confuse the users.

**Comment by wesdevpro** [comment]
> 2\. If "click" trigger is combined with "hover", the dropdown contents won't be closed by moving the pointer out of the trigger once users click

Tested on Windows 10 with Chrome browser.

![image](https://github.com/buefy/buefy/assets/11604664/7bf226fd-a06b-49b9-8f6c-1f73625369b7)
![image](https://github.com/buefy/buefy/assets/11604664/7b8c71f0-098f-42fb-8d53-287ecbc38dad)
Click me works as expected. Hovering the hover button over does not work.

**Comment by kikuomax** [comment]
@wesdevpro Hover is suppressed if the screen is narrower than 1024px (`$dropdown-mobile-breakpoint = $desktop`).

**Comment by kikuomax** [comment]
@wesdevpro I have added a hint:
![image](https://github.com/buefy/buefy/assets/3257531/5555a262-45ff-468c-a751-e539103fa1b9)

**Comment by wesdevpro** [comment]
> 2\. If "click" trigger is combined with "hover", the dropdown contents won't be closed by moving the pointer out of the trigger once users click on the trigger. This might confuse the users.

In my opinion, making that note in the docs is sufficient enough to prevent downside 2. Of course this is assuming developers do not require the "click" trigger to be combined with "hover"

**Comment by kikuomax** [comment]
@wesdevpro I found the explanations contradicting.
"Dropdowns with `hoverable` prop won't change its behavior" vs "Hover is suppressed on a mobile screen".

**Comment by wesdevpro** [comment]
> "Dropdowns with `hoverable` prop won't change its behavior"

Seeing that now is contradicting 😅

**Comment by kikuomax** [comment]
I started to think we should keep the original statement "Dropdowns with hoverable prop won't change its behavior". I will do some experiments around "touchstart" events to detect not only a narrow screen but actual mobile devices.

**Comment by wesdevpro** [comment]
> I started to think we should keep the original statement "Dropdowns with hoverable prop won't change its behavior". I will do some experiments around "touchstart" events to detect not only a narrow screen but actual mobile devices.

Sound slike a plan!

**Comment by kikuomax** [comment]
@glumb @wesdevpro I have refined the behavior. Now "hover" trigger works differently on touch devices or non-touch devices (e.g., PC):
- Touch devices: it works like "click" trigger. When the trigger is tapped, the dropdown contents pop up as a modal if the screen is narrow, otherwise show up under the trigger.
- Non-touch devices (e.g., PC): it won't change behavior whether the screen is narrow or not. The dropdown contents show up under the trigger if the pointer is on the trigger.

Please check the behavior here: https://deploy-preview-3962--buefy-org.netlify.app/documentation/dropdown

**Comment by glumb** [comment]
Any ETA when this will be live? :)

**Comment by wesdevpro** [comment]
> Any ETA when this will be live? :) BTW thanks so much for fixing this so quickly 👍

When we publish the next and final release from the Core Team for Buefy V2(maybe this week or next week). See #3874

**Comment by wesdevpro** [comment]
> > Any ETA when this will be live? :) BTW thanks so much for fixing this so quickly 👍
> 
> When we publish the next and final release from the Core Team for Buefy V2(maybe this week or next week). See #3874

There are also a few working parts we need to get done to prepare to move Buefy-next here
