### ISSUE TITLE
Feature Request: Loading component at the parent level

### ISSUE THREAD

**Issue by adrlen** [buefy/buefy#425]
Would it be possible to have the loading component not overlaying all the page but just its parent ?

```
<div class="columns">
  <div class="column">
    First column
    <b-loading :active.sync="true" :canCancel="true"></b-loading>
  </div>
  <div class="column">
    Second column
  </div>
</div>
```

In this example, just the first column would be overlayed by the loader.

Thoughts ?

**Comment by nick-beers** [comment]
I've found that the fixed position loader is a little overkill for simple use cases that @adrlen is bringing up as well. If there was a way to have an absolute positioned loader in some capacity vs the fixed position (additional class?) so that we can use a relative class on the parent to force the loader to only overlay the parent that should accomplish this request.

**Comment by adrlen** [comment]
@jtommy Would you accept a PR on this ?

**Comment by jtommy** [comment]
@adrlen Yes! If possibile no a breaking change and we'll review your PR. 
Thanks.

**Comment by jtommy** [comment]
Close https://github.com/buefy/buefy/commit/f42665a338b442f91bd5551174e3214796bd3ac8
