### ISSUE TITLE
Checkable Table With @click

### ISSUE THREAD

**Issue by tytondon1234** [buefy/buefy#445]
Hey guys!

Another question from me and thank you for all your help so far! It is fantastic! Anyways, I have a checkable table that also has @click. The issue is when I attempt to check a box it automatically runs the function associated with the @click. Normally, this isn't an issue, but for me that function takes me to a different tab. Is there a way that I can distinguish between the two? So if a user clicks on the check box it will select the checkbox and not run the function in the @click and vice-versa?

**Comment by jtommy** [comment]
@tytondon1234 Is your row selectable ? If you use `@click` to intercept select row you might watch `selected` data. Otherwise you should save a old array of checked row and compare it for every click to know if the checkbale state isn't changed (in this case it isn't a click on checkbox).

**Comment by tytondon1234** [comment]
Hey @jtommy,

Okay, so watch selected data and check it against the length of the checked row? Or something like that?

**Comment by jtommy** [comment]
Watching select data you intercept when a row is selected but if you don't listen other clicks on selected row (only one). I don't know your project but it could be enough about your request. Otherwise, yes you can check checked rows length to know if is a check click event or row click event in your click listener.
