### ISSUE TITLE
On hover/mouseover prevent snackbar notification from disappearing

### ISSUE THREAD

**Issue by feelslike1929** [buefy/buefy#667]
### Overview of the problem

**Buefy** version: [0.6.3]
**Vuejs** version: [2.5.13]
**OS/Browser**: Ubuntu 16, Chrome

### Description

An option to prevent the closing / pause the duration of a snackbar notfication would be very handy.

### Steps to reproduce

1. trigger snackbar notification
2. hover over it

### Expected behavior

On hover over the Snackbar notification, prevent it from disappearing.

### Actual behavior

It disappears after the specified duration.

**Comment by jtommy** [comment]
We have just add a new prop, at the moment. See https://github.com/buefy/buefy/issues/634

**Comment by szmarczak** [comment]
Is it possible to reopen this issue? #634 haven't solved this.

**Comment by jtommy** [comment]
What's the problem?

**Comment by szmarczak** [comment]
@jtommy Thanks for the quick response, I really appreciate it. 

The problem is when having a snackbar delete notification, people who hover mouse on the box may think for a while. When they finished deciding whether undo the operation or not, the box had disappeared already. That may be quite annoying.

There's a workaround here: set `indefinite` to `true` and listen for the `mouseover`/`mouseout` events. Then, call `snackbarComponent.close()` if mouse is out and time is up.

I can send a PR if needed :)

**Comment by jtommy** [comment]
Ok but what do you want add to snackbar?

**Comment by szmarczak** [comment]
@jtommy Hmm, does `pauseOnHover` option sound good?

**Comment by szmarczak** [comment]
> I know your need but it think it's a edge case to be honest.

Sure, I just wanted to suggest a solution. It would be nice to hear other people's thoughts about it :)

**Comment by kimfaint** [comment]
I'm looking at this issue at the moment in relation to [WCAG guideline 2.2 Enough Time](https://www.w3.org/WAI/WCAG21/quickref/?currentsidebar=%23col_overview&versions=2.0&levels=aaa&techniques=advisory&technologies=smil%2Cpdf%2Cflash%2Csl#enough-time).  Seems like the `pauseOnHover` idea would extend the time an impaired user would have to read the snackbar content before it disappears.
