### ISSUE TITLE
.modal-content width incorrect

### ISSUE THREAD

**Issue by Youdaman** [buefy/buefy#905]
**Buefy** version: [0.6.6]

The docs for modal components say the default width is 960 whereas the modal.sass has `.modal-content` width set to 640px and so modals display at 640 even when width is set higher than 640, and the width param only sets the max-width.

Possible fix is to override with:
```
.modal-content {
  width: auto !important;
}
```
To ensure width param of modal component is used.

**Comment by yxngl** [comment]
I am also confused with the purpose of `width` parameter of Modal. It seemingly only sets the max-width, while the width is from Bulma's `$modal-content-width` variable which defaults to 640px.

So in order to use a modal wider than 960px, I have to change `$modal-content-width` and give Modal the same value to `width` as well.
