### ISSUE TITLE
Dynamically changing Field Type does not update icon

### ISSUE THREAD

**Issue by chrisdonnelly** [buefy/buefy#909]
Dynamically changing Buefy field type from is-warning to is-success based on a v-bind type and a $data value.  Field colour is changing correctly but icon is not changing from 'alert-circle' to 'check'.

Buefy version: [0.6.6]
Vuejs version: [2.5.16]
Chrome:  67.0.3396.99
<img width="1367" alt="screen shot 2018-07-16 at 12 01 48" src="https://user-images.githubusercontent.com/29203252/42756034-5a18703a-88f2-11e8-9f51-f871ae1aba78.png">
<img width="1368" alt="screen shot 2018-07-16 at 12 02 08" src="https://user-images.githubusercontent.com/29203252/42756039-5e8a1be6-88f2-11e8-90da-1482382b32e2.png">
![screen shot 2018-07-16 at 12 02 32](https://user-images.githubusercontent.com/29203252/42756041-61484a24-88f2-11e8-934d-2306801f40e8.png)
![screen shot 2018-07-16 at 12 16 06](https://user-images.githubusercontent.com/29203252/42756044-6352ce3e-88f2-11e8-8fc5-35c2b27abed6.png)
![screen shot 2018-07-16 at 12 16 36](https://user-images.githubusercontent.com/29203252/42756047-6549e66e-88f2-11e8-86ed-6a33b8c1b6ba.png)

**Comment by jtommy** [comment]
@chrisdonnelly I have no issue about it, for example: https://codepen.io/anon/pen/KBVOOm?editors=1010.
Are you using FontAwesome as `defaultIconPack` config ?

**Comment by chrisdonnelly** [comment]
![screen shot 2018-07-16 at 13 15 41](https://user-images.githubusercontent.com/29203252/42758154-6967c2ae-88fa-11e8-804b-e5efe04ab2d4.png)

**Comment by jtommy** [comment]
@chrisdonnelly I think there is something in your code. Do you take a look to my example code?

**Comment by chrisdonnelly** [comment]
Yes.  Code seems fine.  You can see from the Vue.JS dev tools captures above that the field type is being changed and updated and that the icon type is being changed and updated.  Note that in the second capture the field is now 'is-success", the icon is now 'check' but the element still shows 'alert-circle'.

**Comment by chrisdonnelly** [comment]
You can see below that the field type has been updated to is-success (and the colour has changed appropriately), the icon has also been updated to check in the vue props.  

However looking at the html element - the SVG is still exclamation circle.  

<img width="1381" alt="screen shot 2018-07-16 at 17 52 00" src="https://user-images.githubusercontent.com/29203252/42772164-7dd0b2e2-8921-11e8-898e-66b73bbabeaa.png">

<img width="1440" alt="screen shot 2018-07-16 at 17 24 17" src="https://user-images.githubusercontent.com/29203252/42772166-800f7a70-8921-11e8-8834-7fd7d2c62f2d.png">

**Comment by jtommy** [comment]
It's very strange.
Did you import font awesome using `"@fortawesome/fontawesome-free-webfonts"` ? And for example:
```
$fa-font-path: "~@fortawesome/fontawesome-free-webfonts/webfonts";
@import "~@fortawesome/fontawesome-free-webfonts/scss/fontawesome";
@import "~@fortawesome/fontawesome-free-webfonts/scss/fa-regular";
@import "~@fortawesome/fontawesome-free-webfonts/scss/fa-solid";
@import "~@fortawesome/fontawesome-free-webfonts/scss/fa-brands";
```

**Comment by chrisdonnelly** [comment]
<img width="594" alt="screen shot 2018-07-16 at 21 16 12" src="https://user-images.githubusercontent.com/29203252/42781246-811b6912-893d-11e8-9a8b-adc29026d898.png">

**Comment by jtommy** [comment]
@chrisdonnelly Same error if you start from success to danger ?
At the moment I can't replicate it to be honest.

**Comment by vlazar** [comment]
With config mentioned here changing icon dynamically is not working when using Font Awesome SVG icons.

To make it work with Font Awesome additionally `defaultIconComponent` is needed (you need to install `@fortawesome/vue-fontawesome`  first):

```js
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";
Vue.component('vue-fontawesome', FontAwesomeIcon);

Vue.use(Buefy, {
  defaultIconComponent: 'vue-fontawesome',
  defaultIconPack: 'fas'
});
```

**Comment by jtommy** [comment]
It isn't really true because you can use CSS version

**Comment by vlazar** [comment]
@jtommy Can you elaborate what do you mean use CSS version? I haven't found a way for font awesome icons to work when changed dynamically without `defaultIconComponent: 'vue-fontawesome'`. If I use material design icons it works without it just fine.

**Comment by jtommy** [comment]
The Buefy docs uses the npm package with sass/CSS fonts

**Comment by vlazar** [comment]
@jtommy Thank you!

This issue is only for SVG icons. Maybe updating the issue title would make it more clear.

Seems like @chrisdonnelly was confused why dynamically changing icons is not working for Font Awesome SVG icons. I was confused as well and it took me a while to find why it's not working and make it work.

I've used a codepen example https://github.com/buefy/buefy/issues/909#issuecomment-405222094 , fixed it and saw it's working but was using material design icons, not font awesome. So I've updated it to use Font Awesome SVG icons and it stopped working. Then I found this:

The doc here https://buefy.org/documentation/icon/#fontawesome mentions this:

> You can set the defaultIconComponent constructor option to render icons with the vue-fontawesome component.

You can do it, yes. It's just not obvious why would you?

Correct me if I'm wrong, but the reason seems to be that **for SVG icons it is required** so that they can be changed dynamically. Otherwise only the color changes, as already mentioned in this issue:

> Field colour is changing correctly but icon is not changing from 'alert-circle' to 'check'.

So maybe it's worth mentioning explicitly in buefy docs that for SVG icons you need to use `vue-fontawesome` component to make it work correctly?

**Comment by jtommy** [comment]
It's no completely right, you can create a your component that shows the icons. Vue-fontawaome is a ready component with good API but works only with FA

**Comment by vlazar** [comment]
I get your point. Sure, I can create whatever custom component needed.

To clarify: I'm not trying to put a blame on buefy or something, I just want some clarity.

Let me ask it this way instead:
- Should user expect buefy built-in field component to work with Font Awesome SVG icons when `type="is-danger"` is changed to `type="is-success"` dynamically?
- If yes, I think current docs are not clear enough about how to achieve it. That's all I was worried about in my original comment https://github.com/buefy/buefy/issues/909#issuecomment-683318502.

Maybe it's not an issue and it's just me who feels confused. And the author of this issue.

**Comment by lenzls** [comment]
Late to the party, but wanted to thank @vlazar. I ran into exactly the same issue, and adding `defaultIconComponent: 'vue-fontawesome',` did the trick for me as well.

This wasn't intuitive at all to me.

**Comment by tgrushka** [comment]
I'm sorry, but three years after this issue was opened, having to rely on an external dependency to fix this is totally ridiculous. That component totally breaks my setup and would require reworking my entire frontend just to workaround this one bug. I have no problem using the JavaScript FA SVGs anywhere else.

I think the problem lies in the fact that the Icon Buefy component is not using a key. This makes it refuse to re-render when it is dynamically changed within controls, in Buefy table colums, etc.

Why not just set the `<i :key...>` similarly to the `<i :class...>` in the Icon component to force Vue to re-render it when it changes?

```vue
<template>
    <span class="icon" :class="[newType, size]">
        <i
            v-if="!useIconComponent"
            :class="[newPack, newIcon, newCustomSize, customClass]"/>

        <component
            v-else
            :is="useIconComponent"
            :icon="[newPack, newIcon]"
            :size="newCustomSize"
            :class="[customClass]"/>
    </span>
</template>
```

**Comment by jtommy** [comment]
Why do you need key ?

**Comment by tgrushka** [comment]
Dynamic keys in Vue force components to re-render when they are changed:

https://michaelnthiessen.com/force-re-render/

**Comment by jtommy** [comment]
Is there a "cache" issue with SVG icon ?
